name: todo_app
description: "健康习惯与日程管理 - 帮助你培养好的健康习惯"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.2
  shared_preferences: ^2.3.5
  timezone: ^0.10.0
  share_plus: ^10.1.4
  file_picker: ^8.1.7
  flutter_slidable: ^3.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
